// Kontiva MVP — Documents mock data
// Registro de todos os documentos enviados para o Kontiva pela carteira:
// contratos, aditivos, planilhas de cobrança, notas fiscais etc.
// Cada documento carrega cliente, contrato (se aplicável), tipo, status de
// processamento pela IA, tamanho, data de envio e quem enviou.

const DOC_TYPE_META = {
  contract:  { label: "Contrato",       icon: "doc" },
  amendment: { label: "Aditivo",        icon: "doc" },
  billing:   { label: "Lançamentos",    icon: "sheet" },
  invoice:   { label: "Nota fiscal",    icon: "doc" },
  receipt:   { label: "Comprovante",    icon: "doc" },
  statement: { label: "Extrato",        icon: "sheet" },
};

const DOC_STATUS_META = {
  processed: { label: "Processado",        className: "processed" },
  review:    { label: "Aguardando revisão", className: "review" },
  processing:{ label: "Processando",        className: "processing" },
  failed:    { label: "Falhou",             className: "failed" },
  archived:  { label: "Arquivado",          className: "archived" },
};

// Documentos listados por ordem decrescente de envio. Mock realista — mistura
// de contratos processados com insights, planilhas de cobrança recentes, e
// alguns itens em estados intermediários (processando, falhou, revisão).
const DOCUMENTS = [
  {
    id: "DOC-2043",
    name: "Contrato_Horizonte_Matriz_2024.pdf",
    type: "contract",
    clientId: "horizonte",
    clientName: "Construtora Horizonte Ltda.",
    contractId: "HRZ-01",
    contractLabel: "Matriz · SP",
    sizeKB: 842,
    pages: 14,
    uploadedAt: "22/04/2026 · 14:32",
    uploadedBy: "Marcos Guedes",
    status: "processed",
    insight: "3 cláusulas de reajuste extraídas · IPCA anual em março",
    isDemo: true,
  },
  {
    id: "DOC-2042",
    name: "Lancamentos_Horizonte_Abr2026.xlsx",
    type: "billing",
    clientId: "horizonte",
    clientName: "Construtora Horizonte Ltda.",
    contractId: "HRZ-01",
    contractLabel: "Matriz · SP",
    sizeKB: 94,
    rows: 128,
    uploadedAt: "22/04/2026 · 14:38",
    uploadedBy: "Marcos Guedes",
    status: "processed",
    insight: "R$ 364 de subfaturamento identificados em 3 meses",
    isDemo: true,
  },
  {
    id: "DOC-2041",
    name: "Aditivo_02_Lumen_Holding.pdf",
    type: "amendment",
    clientId: "lumen",
    clientName: "Lumen Energia Renovável S.A.",
    contractId: "LMN-01",
    contractLabel: "Holding",
    sizeKB: 316,
    pages: 4,
    uploadedAt: "21/04/2026 · 10:12",
    uploadedBy: "Paula Tavares",
    status: "review",
    insight: "Cláusula 7.2 alterada — revisar percentual de reajuste",
  },
  {
    id: "DOC-2040",
    name: "Contrato_Lumen_Usina_MG.pdf",
    type: "contract",
    clientId: "lumen",
    clientName: "Lumen Energia Renovável S.A.",
    contractId: "LMN-02",
    contractLabel: "Usina Minas Gerais",
    sizeKB: 1120,
    pages: 22,
    uploadedAt: "20/04/2026 · 16:47",
    uploadedBy: "Paula Tavares",
    status: "processed",
    insight: "Índice IGP-M · aniversário em setembro",
  },
  {
    id: "DOC-2039",
    name: "Lancamentos_Lumen_Abr2026.xlsx",
    type: "billing",
    clientId: "lumen",
    clientName: "Lumen Energia Renovável S.A.",
    contractId: null,
    contractLabel: "Todos os contratos",
    sizeKB: 212,
    rows: 341,
    uploadedAt: "20/04/2026 · 09:03",
    uploadedBy: "Paula Tavares",
    status: "processed",
    insight: "R$ 2.100 cobrados acima — auditoria aberta",
  },
  {
    id: "DOC-2038",
    name: "Contrato_CasaCor_Simples.pdf",
    type: "contract",
    clientId: "casacor",
    clientName: "Casa & Cor Interiores ME",
    contractId: "CAC-01",
    contractLabel: "Simples Nacional",
    sizeKB: 508,
    pages: 9,
    uploadedAt: "19/04/2026 · 11:21",
    uploadedBy: "Juliana Nunes",
    status: "processed",
    insight: "IPCA anual · fevereiro · sem pegadinhas",
  },
  {
    id: "DOC-2037",
    name: "NFSe_CasaCor_042026.pdf",
    type: "invoice",
    clientId: "casacor",
    clientName: "Casa & Cor Interiores ME",
    contractId: "CAC-01",
    contractLabel: "Simples Nacional",
    sizeKB: 76,
    pages: 1,
    uploadedAt: "19/04/2026 · 11:24",
    uploadedBy: "Juliana Nunes",
    status: "archived",
    insight: null,
  },
  {
    id: "DOC-2036",
    name: "Contrato_Nordeste_Matriz_Petrolina.pdf",
    type: "contract",
    clientId: "nordeste-agri",
    clientName: "Nordeste Agropecuária S.A.",
    contractId: "NAG-01",
    contractLabel: "Matriz · Petrolina",
    sizeKB: 1340,
    pages: 28,
    uploadedAt: "18/04/2026 · 15:55",
    uploadedBy: "Marcos Guedes",
    status: "processed",
    insight: "Aniversário em junho · IPCA precisa entrar no próximo boleto",
  },
  {
    id: "DOC-2035",
    name: "Contrato_Nordeste_Filial_Juazeiro.pdf",
    type: "contract",
    clientId: "nordeste-agri",
    clientName: "Nordeste Agropecuária S.A.",
    contractId: "NAG-02",
    contractLabel: "Filial · Juazeiro",
    sizeKB: 1180,
    pages: 24,
    uploadedAt: "18/04/2026 · 15:58",
    uploadedBy: "Marcos Guedes",
    status: "processed",
    insight: "Mesmas cláusulas do contrato-matriz",
  },
  {
    id: "DOC-2034",
    name: "Lancamentos_Vox_Abr2026.xlsx",
    type: "billing",
    clientId: "vox-clinicas",
    clientName: "Vox Clínicas Odontológicas",
    contractId: null,
    contractLabel: "3 unidades",
    sizeKB: 184,
    rows: 287,
    uploadedAt: "17/04/2026 · 13:40",
    uploadedBy: "Paula Tavares",
    status: "processing",
    insight: null,
  },
  {
    id: "DOC-2033",
    name: "Contrato_PraiaViva_Principal.pdf",
    type: "contract",
    clientId: "praia-viva",
    clientName: "Praia Viva Hotelaria Ltda.",
    contractId: "PRV-01",
    contractLabel: "Contrato principal",
    sizeKB: 624,
    pages: 12,
    uploadedAt: "17/04/2026 · 10:05",
    uploadedBy: "Juliana Nunes",
    status: "processed",
    insight: "Cliente novo · primeira cobrança ainda não emitida",
  },
  {
    id: "DOC-2032",
    name: "Contrato_Pinheiro_Advocacia.pdf",
    type: "contract",
    clientId: "pinheiro-adv",
    clientName: "Pinheiro & Associados Advocacia",
    contractId: "PIN-01",
    contractLabel: "Contrato contábil",
    sizeKB: 488,
    pages: 8,
    uploadedAt: "15/04/2026 · 09:22",
    uploadedBy: "Marcos Guedes",
    status: "processed",
    insight: "IPCA · maio · reajuste já aplicado",
  },
  {
    id: "DOC-2031",
    name: "Contrato_Pinheiro_Folha.pdf",
    type: "contract",
    clientId: "pinheiro-adv",
    clientName: "Pinheiro & Associados Advocacia",
    contractId: "PIN-02",
    contractLabel: "Folha de pagamento",
    sizeKB: 412,
    pages: 7,
    uploadedAt: "15/04/2026 · 09:25",
    uploadedBy: "Marcos Guedes",
    status: "processed",
    insight: "Folha de 18 profissionais — IPCA em maio",
  },
  {
    id: "DOC-2030",
    name: "Contrato_Artemis_Matriz_ilegivel.pdf",
    type: "contract",
    clientId: "artemis-moda",
    clientName: "Artemis Moda Feminina",
    contractId: "ART-01",
    contractLabel: "Matriz",
    sizeKB: 298,
    pages: 6,
    uploadedAt: "14/04/2026 · 17:18",
    uploadedBy: "Paula Tavares",
    status: "failed",
    insight: "PDF escaneado em baixa resolução — reenviar original",
  },
  {
    id: "DOC-2029",
    name: "Lancamentos_Artemis_Abr2026.xlsx",
    type: "billing",
    clientId: "artemis-moda",
    clientName: "Artemis Moda Feminina",
    contractId: "ART-01",
    contractLabel: "Matriz",
    sizeKB: 132,
    rows: 196,
    uploadedAt: "14/04/2026 · 17:25",
    uploadedBy: "Paula Tavares",
    status: "review",
    insight: "IPCA não aplicado no aniversário — R$ 180/mês",
  },
  {
    id: "DOC-2028",
    name: "Extrato_Banco_Nordeste_Mar2026.pdf",
    type: "statement",
    clientId: "nordeste-agri",
    clientName: "Nordeste Agropecuária S.A.",
    contractId: null,
    contractLabel: "Apoio · conciliação",
    sizeKB: 96,
    pages: 3,
    uploadedAt: "12/04/2026 · 08:44",
    uploadedBy: "Marcos Guedes",
    status: "archived",
    insight: null,
  },
];

const DOCUMENTS_SUMMARY = {
  total: DOCUMENTS.length,
  processed: DOCUMENTS.filter(d => d.status === "processed").length,
  review: DOCUMENTS.filter(d => d.status === "review").length,
  processing: DOCUMENTS.filter(d => d.status === "processing").length,
  failed: DOCUMENTS.filter(d => d.status === "failed").length,
  lastUpload: "hoje · 14:38",
};

Object.assign(window, {
  DOCUMENTS, DOC_TYPE_META, DOC_STATUS_META, DOCUMENTS_SUMMARY,
});
